<?php


$title = 'Add new class';
$this->headTitle($title);

$this->headScript()->appendFile($this->basePath('/js/ckeditor/ckeditor.js'));
$this->headScript()->appendFile($this->basePath('/js/ckeditor/adapters/jquery.js'));
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form->setAttribute('action', $this->url('classe', array('action' => 'add')));
$form->prepare();
echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('name'));
echo "<br />";
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();
?>
<script charset="utf-8">
	$('textarea').ckeditor();
</script>
